<?php

/**
 * @file
 * Services api for LiveTime.
 */


/**
 * Implements hook_menu().
 * 
 */
function service_menu() {

	$items['api/v1/user/login'] = array(
		'title' => 'Login',
	    'description' => 'Api for login.',
	    'page callback' => 'service_resource_user_login',
	    'access callback' => TRUE,
	    'file' => 'service.resource.user.inc',
	);

	$items['api/v1/user/signup'] = array(
		'title' => 'Sign up',
		'description' => 'Api for signup',
		'page callback' => 'service_resource_user_signup',
		'access callback' => TRUE,
		'file' => 'service.resource.user.inc',
	);

	$items['api/v1/broadcast/index'] = array(
		'title' => 'Broadcast',
		'description' => 'Api for broadcast',
		'page callback' => 'service_resource_broadcast_index',
		'access callback' => TRUE,
		'file' => 'service.resource.broadcast.inc',
	);

	$items['api/v1/broadcast/create'] = array(
		'title' => 'Create Broadcast',
		'description' => 'Api for creating broadcast',
		'page callback' => 'service_resource_broadcast_create',
		'access callback' => TRUE,
		'file' => 'service.resource.broadcast.inc',
	);

	return $items;
}